### PR TITLE
R package setup

### PR DESCRIPTION
**Pull request by pdiakumis**
Transferring the LINX part of https://github.com/umccr/gpgr to this separate repo for more flexibility.

- Included COLO829v003T data for tests and examples.
  - I shrank the plots by 95% due to size, so they're just a blur now.
- Website should show up at https://umccr.github.io/linxreport/ (eventually).
- Enhanced the README a bit.
- Refactored the Rmd a bit by moving most of its functions into `R/`. 
- Also refactored some CLI code.
- I've kept the VCCC icon - not sure if we should just get rid of it (@scwatts / @ohofmann see screenshot below)?
- I've removed any mentions of UMCCR from the report itself, I just kept a link back to the GitHub repo under the title.
- Moved from argparse to optparse for the CLI since it's a pure R pkg with no Python requirements.

ss 2024-02-08 at 23 33 36

### CODE REVIEW

**Comment by scwatts** [comment]
Looks amazing. The logo could eventually made to be optional and set by the user - I have no objection to it though!

**Comment by scwatts** [comment]
I noticed that the README.md has a a table at the beginning but I suspect this is done intentionally, wanted to check nonetheless

image

**Comment by ohofmann** [comment]
@pdiakumis Keep the logo until Zoe is back and comes up with a new one ;)

**Comment by pdiakumis** [comment]
Thanks both. I fixed a couple things, tried to get a satisfactory balance between the README showing up in GitHub and the pkgdown website, think it looks better now.
Merging and bumping the version to 1.0.

**Pull request merged**
